version: '3'
services:
  cassandra1:
    image: cassandra:4.1
    container_name: cassandra1
    network_mode: "host"
    environment:
      - CASSANDRA_SEEDS=10.0.1.4
      - CASSANDRA_LISTEN_ADDRESS=10.0.1.4
      - CASSANDRA_BROADCAST_ADDRESS=10.0.1.4
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - ./data-node1:/var/lib/cassandra
